buildscript {
    repositories {
        mavenLocal()
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
    dependencies {
        if (rootProject.name == 'fabric-26.2') {
            classpath 'net.fabricmc:fabric-loom:1.17.17'
        } else if (rootProject.name == 'fabric-26.1') {
            classpath 'net.fabricmc:fabric-loom:1.15.5'
        } else {
            classpath 'net.fabricmc:fabric-loom:1.14.10'
        }
    }
}

apply plugin: rootProject.name.startsWith('fabric-26.') ? 'net.fabricmc.fabric-loom' : 'fabric-loom'
apply plugin: 'maven-publish'
apply from: './fabric.gradle'
